repos:
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
      - id: prettier

  - repo: local
    hooks:
      - id: oxlint
        name: oxlint
        entry: pnpm run lint
        language: system
        files: \.(ts)$
        pass_filenames: false

      - id: typecheck
        name: TypeScript typecheck
        entry: pnpm run typecheck
        language: system
        files: \.(ts)$
        pass_filenames: false
